# Generated by Django 3.1.1 on 2020-09-07 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Soldier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_names', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('regiment', models.CharField(max_length=30)),
                ('rank', models.CharField(max_length=10)),
                ('number', models.CharField(max_length=20)),
            ],
        ),
    ]
