# Generated by Django 3.1.1 on 2020-09-07 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soldiers_viewer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soldier',
            old_name='number',
            new_name='soldier_number',
        ),
        migrations.RenameField(
            model_name='soldier',
            old_name='rank',
            new_name='soldier_rank',
        ),
    ]
