# Generated by Django 3.1.1 on 2020-09-07 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soldiers_viewer', '0004_auto_20200907_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldier',
            name='regiment',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='soldier_rank',
            field=models.CharField(max_length=20),
        ),
    ]
