# Generated by Django 3.1.1 on 2020-09-07 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soldiers_viewer', '0005_auto_20200907_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldier',
            name='other_names',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='surname',
            field=models.CharField(max_length=50),
        ),
    ]
