# Generated by Django 3.1.1 on 2020-09-08 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soldiers_viewer', '0006_auto_20200907_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldier',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='regiment',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='soldier_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='soldier_rank',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
