# Generated by Django 3.1.1 on 2021-05-23 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soldiers_viewer', '0007_auto_20200908_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldier',
            name='lat',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='soldier',
            name='lng',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
    ]
